version: '3.2'

services:
  mongo:
    image: mongo
    container_name: mongo-chat
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
